In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from scipy.stats import chi2_contingency
import seaborn as sns
import os
import math

In [18]:
path = "/Users/alicedrozd/Documents/2024/MIDS/W241/Final Project/Civil Affairs Network - FINAL_December 7, 2024_14/Raw-Table 1.csv"
raw_data = pd.read_csv(path, header=[0,1])

In [19]:
raw_data = pd.DataFrame(raw_data)
raw_data

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,NQ4.9_Click Count,Q2.4_1,NQ4.11_First Click,NQ4.11_Last Click,NQ4.11_Page Submit,NQ4.11_Click Count,Q2.5_11,transaction_id,Control,Treatment
,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,Timing - Click Count,How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value. - Level of Agreement,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value. - Level of Agreement,transaction_id,Control,Treatment
0,12/6/24 12:36,12/6/24 12:38,IP Address,172.56.70.103,100,75,True,12/6/24 12:38,R_1iPQOVMwHTh3kbQ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6mFiGCmrgdo49JhWi0rTfh,True,False
1,12/6/24 12:37,12/6/24 12:38,IP Address,47.159.143.250,100,68,True,12/6/24 12:38,R_3rOYQJ2oAekAzNa,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6d4bLN1fEsHRvj5riTUQG1,True,False
2,12/6/24 12:37,12/6/24 12:38,IP Address,172.59.136.93,100,73,True,12/6/24 12:38,R_5KHoSb8sMKNBb7p,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69Gr7w21tq1aPXvuIZF8Ej,True,False
3,12/6/24 12:36,12/6/24 12:38,IP Address,72.255.84.2,100,106,True,12/6/24 12:38,R_7Q6AkFhK5jPeiUp,NaN,...,1.0,91.0,5.948,6.560,7.223,2.0,75.0,5Vn6oUzXkYi1WQMvPaFwuv,False,True
4,12/6/24 12:36,12/6/24 12:38,IP Address,174.193.92.60,100,113,True,12/6/24 12:38,R_6UgZd5d90ABqs6J,NaN,...,2.0,100.0,2.998,4.224,4.701,2.0,79.0,05Qo3FjXCiqKxYwvm7jTnZ,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,12/7/24 12:24,12/7/24 12:24,IP Address,35.146.159.13,100,0,True,12/7/24 12:24,R_7EaM67gnevFNztH,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2Pdlrta8UqwnezA6U4SGhl,NaN,NaN
418,12/7/24 12:25,12/7/24 12:25,IP Address,71.91.106.108,100,0,True,12/7/24 12:25,R_3mlTjvXTb7472zs,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7HL4hI4bv03gAIGJhRPhBV,NaN,NaN
419,12/7/24 12:26,12/7/24 12:26,IP Address,174.196.130.188,100,0,True,12/7/24 12:26,R_5k1dXVZqAa8jjzA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3WZZWK0MLPh35xjDfUawCq,NaN,NaN
420,12/7/24 13:03,12/7/24 13:03,IP Address,75.143.209.219,100,0,True,12/7/24 13:03,R_7ioy3XXGY9N2UMN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4rUnRBH9gxmclKhuf8p707,NaN,NaN
421,12/7/24 13:44,12/7/24 13:44,IP Address,104.184.218.244,100,0,True,12/7/24 13:44,R_6lymk8XT6KgkbzQ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7jFvjLN727UiSmbOmSGyPQ,NaN,NaN

In [24]:
422-226

196

In [21]:
raw_data[('Q1.5_0')].columns

Index(['How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value.\n\n\n\n\n"Undocumented workers are often exploited in the U.S., despite being a crucial part of the nation’s economy. To protect their rights and drive economic growth, we should take immediate steps to significantly expand the availability of work visas." - Level of Agreement'], dtype='object')

In [22]:
began_treatment = [
    not math.isnan(x) for x in raw_data[
    ('NQ4.1_First Click', 'Timing - First Click')
    ]
]

began_control = [
    not math.isnan(x) for x in raw_data[
    ('NQ3.1_First Click', 'Timing - First Click')
    ]
]

began_survey = pd.concat([raw_data[began_treatment], raw_data[began_control]])

In [23]:
began_survey

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,NQ4.9_Click Count,Q2.4_1,NQ4.11_First Click,NQ4.11_Last Click,NQ4.11_Page Submit,NQ4.11_Click Count,Q2.5_11,transaction_id,Control,Treatment
,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,Timing - Click Count,How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value. - Level of Agreement,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value. - Level of Agreement,transaction_id,Control,Treatment
3,12/6/24 12:36,12/6/24 12:38,IP Address,72.255.84.2,100,106,True,12/6/24 12:38,R_7Q6AkFhK5jPeiUp,NaN,...,1.0,91.0,5.948,6.560,7.223,2.0,75.0,5Vn6oUzXkYi1WQMvPaFwuv,False,True
4,12/6/24 12:36,12/6/24 12:38,IP Address,174.193.92.60,100,113,True,12/6/24 12:38,R_6UgZd5d90ABqs6J,NaN,...,2.0,100.0,2.998,4.224,4.701,2.0,79.0,05Qo3FjXCiqKxYwvm7jTnZ,False,True
5,12/6/24 12:37,12/6/24 12:38,IP Address,172.59.124.199,100,103,True,12/6/24 12:38,R_3O6p4L2i9egsbwD,NaN,...,2.0,57.0,7.263,8.498,9.162,3.0,46.0,6Cerz3PdRIhQlGqFU9qY59,False,True
6,12/6/24 12:36,12/6/24 12:38,IP Address,97.184.102.170,100,123,True,12/6/24 12:38,R_33PCMPc9E18UIA9,NaN,...,2.0,83.0,1.068,1.664,2.962,2.0,78.0,7F9jGZ6LY15H0ZPOxJCPFb,False,True
13,12/6/24 12:37,12/6/24 12:39,IP Address,68.40.186.50,100,145,True,12/6/24 12:39,R_16tkscW17BTmd45,NaN,...,3.0,55.0,2.611,8.361,9.382,4.0,57.0,6a6PUBbY9AVylVSTuD2TB0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,12/6/24 17:07,12/6/24 17:13,IP Address,99.154.7.135,100,313,True,12/6/24 17:13,R_1wu9Y3lM7Nddieo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0LDrCzevvglJ0P2vJjF9nL,True,False
315,12/6/24 17:16,12/6/24 17:18,IP Address,73.52.101.101,100,161,True,12/6/24 17:18,R_73MtG3bz8VRgSLD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4yh5baSWS17UCjA6QMeICq,True,False
358,12/6/24 18:37,12/6/24 18:40,IP Address,70.124.97.161,100,153,True,12/6/24 18:40,R_7MMzIY6eiDVB5D4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0gjXdXsE6lLaW5MavbasrH,True,False
362,12/6/24 18:51,12/6/24 18:53,IP Address,107.139.134.188,100,119,True,12/6/24 18:53,R_7LJLgpaZUP7AxLX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6B7DkUuUqfrR0JTeWuGi1B,True,False
365,12/6/24 19:12,12/6/24 19:14,IP Address,24.176.250.49,100,143,True,12/6/24 19:14,R_6PsI7BZbHm7gYSt,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06HZ9nJqmXKTKfkxx7Iunx,True,False

In [39]:
raw_data[began_control]

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,NQ4.9_Click Count,Q2.4_1,NQ4.11_First Click,NQ4.11_Last Click,NQ4.11_Page Submit,NQ4.11_Click Count,Q2.5_11,transaction_id,Control,Treatment
,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,Timing - Click Count,How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value. - Level of Agreement,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value. - Level of Agreement,transaction_id,Control,Treatment
0,2024-12-06 12:36:54,2024-12-06 12:38:10,IP Address,172.56.70.103,100,75,True,2024-12-06 12:38:11.352,R_1iPQOVMwHTh3kbQ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6mFiGCmrgdo49JhWi0rTfh,True,False
1,2024-12-06 12:37:06,2024-12-06 12:38:14,IP Address,47.159.143.250,100,68,True,2024-12-06 12:38:15.508,R_3rOYQJ2oAekAzNa,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6d4bLN1fEsHRvj5riTUQG1,True,False
2,2024-12-06 12:37:14,2024-12-06 12:38:28,IP Address,172.59.136.93,100,73,True,2024-12-06 12:38:28.591,R_5KHoSb8sMKNBb7p,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69Gr7w21tq1aPXvuIZF8Ej,True,False
7,2024-12-06 12:37:32,2024-12-06 12:38:53,IP Address,172.59.194.206,100,80,True,2024-12-06 12:38:54.249,R_7WNoeuNB4wYPkYY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7av5fVUhVj93Npzfs26AqM,True,False
8,2024-12-06 12:37:27,2024-12-06 12:38:58,IP Address,172.74.214.55,100,91,True,2024-12-06 12:38:58.697,R_6HxQxzJGMAMxJTj,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1ZkZAsB5vw9ChFRDYbVB8v,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,2024-12-06 17:07:51,2024-12-06 17:13:05,IP Address,99.154.7.135,100,313,True,2024-12-06 17:13:05.704,R_1wu9Y3lM7Nddieo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0LDrCzevvglJ0P2vJjF9nL,True,False
315,2024-12-06 17:16:15,2024-12-06 17:18:57,IP Address,73.52.101.101,100,161,True,2024-12-06 17:18:57.863,R_73MtG3bz8VRgSLD,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4yh5baSWS17UCjA6QMeICq,True,False
358,2024-12-06 18:37:53,2024-12-06 18:40:26,IP Address,70.124.97.161,100,153,True,2024-12-06 18:40:27.074,R_7MMzIY6eiDVB5D4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0gjXdXsE6lLaW5MavbasrH,True,False
362,2024-12-06 18:51:31,2024-12-06 18:53:31,IP Address,107.139.134.188,100,119,True,2024-12-06 18:53:31.591,R_7LJLgpaZUP7AxLX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6B7DkUuUqfrR0JTeWuGi1B,True,False
365,2024-12-06 19:12:25,2024-12-06 19:14:49,IP Address,24.176.250.49,100,143,True,2024-12-06 19:14:49.918,R_6PsI7BZbHm7gYSt,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06HZ9nJqmXKTKfkxx7Iunx,True,False

In [55]:
began_survey['Completed Treatment'] = [
    (not math.isnan(x)) * 1 for x in began_survey[
    ('Q2.5_11', 'How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value. - Level of Agreement')
    ]
]

began_survey['Completed Control'] = [
    (not math.isnan(x)) * 1 for x in began_survey[
    ('Q1.5_0', 'How much do you agree with this statement from 0-100? 0 being the lowest and 100 being the highest. Slide to enter a value.\n\n\n\n\n"Undocumented workers are often exploited in the U.S., despite being a crucial part of the nation’s economy. To protect their rights and drive economic growth, we should take immediate steps to significantly expand the availability of work visas." - Level of Agreement')
    ]
]

In [56]:
began_survey['Treatment'] == True

     Treatment
3         True
4         True
5         True
6         True
13        True
..         ...
271      False
315      False
358      False
362      False
365      False

[226 rows x 1 columns]

In [69]:
began_survey['TreatAssign'] = [x * 1 for x in began_survey[('Treatment', 'Treatment')]]
began_survey['Attrition'] = 1- (began_survey['Completed Treatment'] + began_survey['Completed Control'])
began_survey = began_survey[['NQ2.4','NQ2.5', 'NQ2.6','NQ2.7','NQ2.8','NQ2.9','TreatAssign', 'Completed Treatment', 'Completed Control', 'Attrition']]

In [74]:
treatment_map = {'NQ2.4':'party','NQ2.5':'leaning','NQ2.6':'gender','NQ2.7':'age',
                 'NQ2.8':'race','NQ2.9':'hispanic','NQ2.10':'citizenship',
                 'Q2.1_11':'Q1','Q2.2_11':'Q2','Q2.3_11':'Q3','Q2.4_1':'Q4',
                 'Q2.5_11':'Q5'}
began_survey.rename(columns=treatment_map, inplace=True)

C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\3571170700.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey.rename(columns=treatment_map, inplace=True)

In [79]:
began_survey.columns = began_survey.columns.droplevel(1)

In [80]:
began_survey

,party,leaning,gender,age,race,hispanic,TreatAssign,Completed Treatment,Completed Control,Attrition
3,Republican,Strongly Conservative,man,35-44,White,No,1,1,0,0
4,Democrat,Liberal,woman,55-64,White,No,1,1,0,0
5,Republican,Moderate,woman,35-44,White,No,1,1,0,0
6,Democrat,Lean Liberal,woman,55-64,White,No,1,1,0,0
13,Democrat,Liberal,man,65 or older,Black or African American,No,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...
271,Republican,Moderate,man,25-34,Two or more,Yes,0,0,1,0
315,Democrat,Liberal,man,25-34,Other race,Yes,0,0,1,0
358,Democrat,Moderate,man,18-24,White,Yes,0,0,1,0
362,Democrat,Strongly Liberal,man,18-24,Other race,Yes,0,0,1,0
365,Democrat,Lean Liberal,woman,55-64,White,Yes,0,0,1,0

In [81]:
covariates = ['party','leaning','gender','age','race','hispanic']

In [84]:
# From I. Vaimberg
# turn covariates into one hot encoded columns
df_dummy = pd.get_dummies(began_survey[covariates])

one_hot_covariates = [#'party_Democrat',
 'party_Independent', 'party_Other',
'party_Republican',

'leaning_Conservative', 'leaning_Lean Conservative',
'leaning_Lean Liberal', 'leaning_Liberal', 'leaning_Moderate',
'leaning_Strongly Conservative',
 #'leaning_Strongly Liberal',

#'gender_man',
 'gender_woman',

#'age_18-24',
'age_25-34', 'age_35-44',
'age_45-54', 'age_55-64', 'age_65 or older',

'race_American Indian or Alaska Native', 'race_Asian',
'race_Black or African American',
'race_Native Hawaiian or Other Pacific Islander', 'race_Other race',
'race_Two or more',
#'race_White',

#'hispanic_No',
 'hispanic_Yes',
]


began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]

C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]
C:\Users\tmajidzadeh\AppData\Local\Temp\ipykernel_10612\2428614538.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  began_survey[one_hot_covariates] = df_dummy[one_hot_covariates]

In [ ]:
new_covariates = [#'party_Democrat',
 'party_Independent', 'party_Other',
'party_Republican',

'leaning_Conservative', 'leaning_Lean Conservative',
'leaning_Lean Liberal', 'leaning_Liberal', 'leaning_Moderate',
'leaning_Strongly Conservative',
 #'leaning_Strongly Liberal',

#'gender_man',
 'gender_woman',

#'age_18-24',
'age_25-34', 'age_35-44',
'age_45-54', 'age_55-64', 'age_65 or older',

'race_American Indian or Alaska Native', 'race_Asian',
'race_Black or African American',
'race_Native Hawaiian or Other Pacific Islander', 'race_Other race',
'race_Two or more',
#'race_White',

#'hispanic_No',
 'hispanic_Yes'
]

In [89]:
rs = began_survey


X = rs[['TreatAssign']+one_hot_covariates]#+interaction_cols]
y = rs['Attrition']


X = sm.add_constant(X)
basic_model = sm.OLS(y,X.astype(float))
basic_results = basic_model.fit(cov_type='HC3')
print(basic_results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              Attrition   R-squared:                       0.087
Model:                            OLS   Adj. R-squared:                 -0.017
Method:                 Least Squares   F-statistic:                    0.7732
Date:                Tue, 10 Dec 2024   Prob (F-statistic):              0.762
Time:                        13:12:08   Log-Likelihood:                -52.225
No. Observations:                 226   AIC:                             152.5
Df Residuals:                     202   BIC:                             234.5
Df Model:                          23
Covariance Type:                  HC3
==================================================================================================================
                                                     coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------
const                                             -0.0312      0.098     -0.320      0.749      -0.222       0.160
TreatAssign                                        0.1160      0.047      2.490      0.013       0.025       0.207
party_Independent                                 -0.0521      0.056     -0.935      0.350      -0.161       0.057
party_Other                                       -0.2860      0.227     -1.258      0.208      -0.731       0.159
party_Republican                                  -0.0159      0.065     -0.244      0.807      -0.144       0.112
leaning_Conservative                               0.0023      0.083      0.028      0.978      -0.161       0.166
leaning_Lean Conservative                          0.1772      0.118      1.508      0.132      -0.053       0.408
leaning_Lean Liberal                               0.1262      0.115      1.097      0.273      -0.099       0.352
leaning_Liberal                                    0.0655      0.073      0.898      0.369      -0.078       0.209
leaning_Moderate                                   0.0845      0.054      1.561      0.119      -0.022       0.190
leaning_Strongly Conservative                      0.0610      0.091      0.667      0.505      -0.118       0.240
gender_woman                                       0.0266      0.048      0.551      0.582      -0.068       0.121
age_25-34                                         -0.0460      0.077     -0.595      0.552      -0.198       0.106
age_35-44                                         -0.0413      0.089     -0.464      0.643      -0.216       0.133
age_45-54                                          0.0688      0.091      0.754      0.451      -0.110       0.248
age_55-64                                          0.0835      0.099      0.842      0.400      -0.111       0.278
age_65 or older                                    0.0531      0.109      0.488      0.626      -0.160       0.266
race_American Indian or Alaska Native              0.1042      0.206      0.507      0.612      -0.299       0.507
race_Asian                                        -0.0522      0.088     -0.597      0.551      -0.224       0.119
race_Black or African American                     0.0067      0.068      0.098      0.922      -0.126       0.140
race_Native Hawaiian or Other Pacific Islander    -0.1968      0.152     -1.298      0.194      -0.494       0.100
race_Other race                                    0.0471      0.134      0.351      0.725      -0.215       0.310
race_Two or more                                   0.1034      0.145      0.715      0.475      -0.180       0.387
hispanic_Yes                                      -0.0266      0.083     -0.319      0.750      -0.190       0.137
==============================================================================
Omnibus:                       97.802   Durbin-Watson:                   1.118
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              247.008
Skew:                           2.069   Prob(JB):                     2.31e-54
Kurtosis:                       6.019   Cond. No.                         23.6
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [94]:
began_survey[(began_survey['Attrition'] == 1) & (began_survey['TreatAssign'] == 1)] \
    .groupby('party') \
    .count()[['Attrition']]

             Attrition
party
Democrat             6
Independent          6
Republican           8